const products=[{d:100,p:10},{d:310,p:25},{d:520,p:40,hot:true},{d:1060,p:75},{d:2180,p:145,hot:true},{d:5600,p:350},{d:10000,p:600}];
const $=id=>document.getElementById(id),fmt=n=>n.toLocaleString("ru-RU");let current=null,receiptFile=null;
function showStep(step){$("step1").hidden=step!==1;$("step2").hidden=step!==2;$("step3").hidden=step!==3;$("dot1").classList.toggle("active",step>=1);$("dot2").classList.toggle("active",step>=2);$("dot3").classList.toggle("active",step>=3)}
products.forEach(p=>{const c=document.createElement("article");c.className="product"+(p.hot?" hot":"");c.innerHTML=`${p.hot?'<span class="ribbon">МАШҲУР</span>':""}<div class="gemSmall">💎</div><div class="pack">${fmt(p.d)} алмос</div><div class="old">&nbsp;</div><div class="price">${fmt(p.p)} сомонӣ</div><button class="buy" type="button">Харидан →</button>`;c.querySelector(".buy").onclick=()=>{current=p;receiptFile=null;$("selected").textContent=`💎 ${fmt(p.d)} алмос — ${fmt(p.p)} сомонӣ`;$("playerId").value="";$("orderMsg").textContent="";$("receiptInput").value="";$("previewBox").hidden=true;$("send").disabled=true;$("receiptMsg").textContent="";$("order").hidden=false;showStep(1)};$("products").appendChild(c)});
$("closeOrder").onclick=()=>$("order").hidden=true;
$("continueBtn").onclick=()=>{const id=$("playerId").value.trim();if(id.length<5){$("orderMsg").textContent="Лутфан ID-и дурусти Free Fire-ро ворид кунед.";return}$("orderMsg").textContent="";$("receiptSummary").textContent=`💎 ${fmt(current.d)} алмос • ID: ${id} • ${fmt(current.p)} сомонӣ`;showStep(2)};
$("playerId").oninput=()=>$("playerId").value=$("playerId").value.replace(/[^0-9]/g,"");
$("receiptInput").onchange=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith("image/")){$("receiptMsg").textContent="Лутфан танҳо акси чекро интихоб кунед.";return}receiptFile=f;$("preview").src=URL.createObjectURL(f);$("previewBox").hidden=false;$("send").disabled=false;$("receiptMsg").textContent="Чек интихоб шуд."};
$("remove").onclick=()=>{receiptFile=null;$("receiptInput").value="";$("previewBox").hidden=true;$("send").disabled=true;$("receiptMsg").textContent=""};
$("send").onclick=()=>{if(!receiptFile){$("receiptMsg").textContent="Аввал чеки пардохтро интихоб кунед.";return}showStep(3)};
$("newOrder").onclick=()=>{$("order").hidden=true;$("packages").scrollIntoView({behavior:"smooth"})};